version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: evenly_blog

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
