version: "3"

services:

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    restart: always
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 8008:80
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-net
    depends_on:
      - php-fpm

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  redis:
    image: redis:alpine
    networks:
      - laravel-net

networks:
  laravel-net:

volumes:
  db-data: